#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 13 10:24:48 2020

@author: june
"""

#%%

from urllib.request import urlopen
from bs4 import BeautifulSoup

url = "https://finance.naver.com/sise/"